app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a target="_blank"
                                       href="https://appseed.us/admin-dashboards/flask-dashboard-volt">Flask Volt</a> - Sign IN
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p>    
                            </div>

                            <form method="post" action="" class="mt-4">
                                
                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user-circle"></span></span>
                                        {{ form.username(placeholder="Username", class="form-control") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                                            <label class="form-check-label" for="defaultCheck5">
                                              Remember me
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <a href="{{ url_for('base_blueprint.register') }}" class="small text-right">Register</a>
                                        </div>
                                    </div>

                                </div>
                                <button type="submit" name="login" class="btn btn-block btn-primary">Sign in</button>
                            </form>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="font-weight-normal">
                                    &copy; <a  href="https://themesberg.com" target="_blank">Themesberg</a> 
                                    - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/footer.html
    <footer class="footer section py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-6 mb-4 mb-lg-0">
                    <p class="mb-0 text-center text-xl-left">
                        &copy; <a class="text-primary font-weight-normal" href="https://themesberg.com" target="_blank">Themesberg</a>
                        - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
                    </p>
                </div>

                <div class="col-12 col-lg-6">
                    <!-- List -->
                    <ul class="list-inline list-group-flush list-group-borderless text-center text-xl-right mb-0">
                        <li class="list-inline-item px-0 px-sm-2">
                            <a target="_blank" 
                               href="https://appseed.us/admin-dashboards/flask-dashboard-volt">Flask Volt Dashboard</a>
                        </li>
                    </ul>
                    <!-- End List -->
                </div>
            </div>
        </div>
    </footer>

app/base/templates/includes/navigation.html
        <nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark pl-0 pr-2 pb-0">
            <div class="container-fluid px-0">
              <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                <div class="d-flex">
                  <!-- Search form -->
                  <form class="navbar-search form-inline" id="navbar-search-main">
                    <div class="input-group input-group-merge search-bar">
                        <span class="input-group-text" id="topbar-addon"><span class="fas fa-search"></span></span>
                        <input type="text" class="form-control" id="topbarInputIconLeft" placeholder="Search" aria-label="Search" aria-describedby="topbar-addon">
                    </div>
                  </form>
                </div>
                <!-- Navbar links -->
                <ul class="navbar-nav align-items-center">
                  <li class="nav-item dropdown">
                    <a class="nav-link text-dark mr-lg-3 icon-notifications" data-unread-notifications="true" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="icon icon-sm">
                        <span class="fas fa-bell bell-shake"></span>
                        <span class="icon-badge rounded-circle unread-notifications"></span>
                      </span>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                      <div class="list-group list-group-flush">
                        <a href="#" class="text-center text-primary font-weight-bold border-bottom border-light py-3">Notifications</a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-1.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Jose Leos</h4>
                                    </div>
                                    <div class="text-right">
                                      <small class="text-danger">a few moments ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">Added you to an event "Project stand-up" tomorrow at 12:30 AM.</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-2.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Neil Sims</h4>
                                    </div>
                                    <div class="text-right">
                                      <small class="text-danger">2 hrs ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">You've been assigned a task for "Awesome new project".</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Roberta Casas</h4>
                                    </div>
                                    <div class="text-right">
                                      <small>5 hrs ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">Tagged you in a document called "First quarter financial plans",</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-4.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Joseph Garth</h4>
                                    </div>
                                    <div class="text-right">
                                      <small>1 d ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">New message: "Hey, what's up? All set for the presentation?"</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-5.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Bonnie Green</h4>
                                    </div>
                                    <div class="text-right">
                                      <small>2 hrs ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">New message: "We need to improve the UI/UX for the landing page."</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
                      </div>
                    </div>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link pt-1 px-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <div class="media d-flex align-items-center">
                        <img class="user-avatar md-avatar rounded-circle" alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg">
                        <div class="media-body ml-2 text-dark align-items-center d-none d-lg-block">
                          <span class="mb-0 font-small font-weight-bold">
                            {{ current_user.username }}
                          </span>
                        </div>
                      </div>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-right mt-2">
                      <a class="dropdown-item font-weight-bold" href="/settings.html"><span class="fas fa-cog"></span>Settings</a>
                      <div role="separator" class="dropdown-divider"></div>
                      <a class="dropdown-item font-weight-bold" href="{{ url_for('base_blueprint.logout') }}">
                          <span class="fas fa-sign-out-alt text-danger"></span>Logout</a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
        </nav>

app/base/templates/includes/scripts.html
    <!-- Core -->
    <script src="/static/assets/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    
    <!-- Vendor JS -->
    <script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>
    
    <!-- Slider -->
    <script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>
    
    <!-- Jarallax -->
    <script src="/static/assets/vendor/jarallax/dist/jarallax.min.js"></script>
    
    <!-- Smooth scroll -->
    <script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    
    <!-- Count up -->
    <script src="/static/assets/vendor/countup.js/dist/countUp.umd.js"></script>
    
    <!-- Notyf -->
    <script src="/static/assets/vendor/notyf/notyf.min.js"></script>
    
    <!-- Charts -->
    <script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
    <script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    
    <!-- Datepicker -->
    <script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>
    
    <!-- Simplebar -->
    <script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- Volt JS -->
    <script src="/static/assets/js/volt.min.js"></script>

app/base/templates/includes/sidebar.html
    <nav id="sidebarMenu" class="sidebar d-md-block bg-primary text-white collapse px-4">
        <div class="sidebar-sticky pt-3 mx-auto">
            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="user-avatar lg-avatar mr-4">
                <img src="/static/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white" alt="Bonnie Green">
                </div>
                <div class="d-block">
                <h2 class="h6">
                    {{ current_user.username }}
                </h2>
                <a href="{{ url_for('base_blueprint.logout') }}" class="btn btn-secondary text-dark btn-xs">
                    <span class="mr-2"><span class="fas fa-sign-out-alt"></span></span>Sign Out</a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" class="fas fa-times" data-toggle="collapse"
                    data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation"></a>
            </div>
            </div>
            <ul class="nav flex-column">
            <li class="nav-item  {% if 'dashboard' in segment %} active {% endif %}">
                <a href="/dashboard.html" class="nav-link">
                <span class="sidebar-icon"><span class="fas fa-chart-pie"></span></span>
                <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item  {% if 'transactions' in segment %} active {% endif %}">
                <a href="/transactions.html" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-hand-holding-usd"></span></span>
                    <span>Transactions</span>
                </a>
            </li>
            <li class="nav-item  {% if 'settings' in segment %} active {% endif %}">
                <a href="/settings.html" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-cog"></span></span>
                    <span>Settings</span>
                </a>
            </li>
            <li class="nav-item">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#submenu-app">
                <span>
                    <span class="sidebar-icon"><span class="fas fa-table"></span></span> 
                    Tables
                </span>
                <span class="link-arrow"><span class="fas fa-chevron-right"></span></span> 
                </span>
                <div class="multi-level collapse " role="list" id="submenu-app" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item "><a class="nav-link" href="/bootstrap-tables.html"><span>Bootstrap Tables</span></a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#submenu-pages">
                <span>
                    <span class="sidebar-icon"><span class="far fa-file-alt"></span></span> 
                    Page examples
                </span>
                <span class="link-arrow"><span class="fas fa-chevron-right"></span></span> 
                </span>
                <div class="multi-level collapse " role="list" id="submenu-pages" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item"><a class="nav-link" href="/sign-in.html"><span>Sign In</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/sign-up.html"><span>Sign Up</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/forgot-password.html"><span>Forgot password</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/reset-password.html"><span>Reset password</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/lock.html"><span>Lock</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/page-404.html"><span>404 Not Found</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/page-500.html"><span>500 Server Error</span></a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#submenu-components">
                <span>
                    <span class="sidebar-icon"><span class="fas fa-box-open"></span></span> 
                    Components
                </span>
                <span class="link-arrow"><span class="fas fa-chevron-right"></span></span> 
                </span>
                <div class="multi-level collapse " role="list" id="submenu-components" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item "><a class="nav-link" href="/ui-buttons.html"><span>Buttons</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-notifications.html"><span>Notifications</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-forms.html"><span>Forms</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-modals.html"><span>Modals</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-typography.html"><span>Typography</span></a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('base_blueprint.logout') }}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-sign-out-alt text-danger"></span></span>
                    <span>Logout</span>
                </a>
            </li>            
            <li role="separator" class="dropdown-divider mt-4 mb-3 border-black"></li>
            <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon">
                    <img src="/static/assets/img/brand/light.svg" height="20" width="20" alt="Volt Logo">
                </span>
                <span class="mt-1">Presentation</span>
                </a>
            </li>
            <li class="nav-item">
                <a target="_blank" 
                   href="https://themesberg.com/docs/volt-bootstrap-5-dashboard/getting-started/quick-start/" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon"><span class="fas fa-book"></span></span>
                <span>UI Docs</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="https://themesberg.com" target="_blank" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon">
                    <img src="/static/assets/img/themesberg.svg" height="20" width="20" alt="Themesberg Logo">
                </span>
                <span>Themesberg</span>
                </a>
            </li>
            <li class="nav-item">
                <a target="_blank"
                   href="https://appseed.us" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon"><span class="fas fa-rocket"></span></span>
                <span>AppSeed</span>
                </a>
            </li>
            </ul>
        </div>
    </nav>